name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: Dave-YP
          outputs: dist/snake.svg

      - name: Push generated snake.svg
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
